### ISSUE TITLE
Unable to install the package using pip install command. throwing error: [Errno 2] No such file or directory: 'pipenv'

### ISSUE THREAD

**Issue by akhilrajvc** [pawelzny/dotty_dict#32]

**Comment by pawelzny** [comment]
Hi @akhilrajvc 
I'd like to say its a feature, but it is a bug. I did not provide proper compatibility with both `pip` and `pipenv`. Moreover this repository has only development dependencies which should never affect you.

There are 2 fast solutions and few slower.

**fast**
1. Firstly install pipenv `pip install pipenv`, and then `pip install dotty-dict`.
2. Copy-paste `dotty_dict.py` file from my repository. It is one file, without dependencies. Dotty Dict is under MIT license. You can make a copy without any restrictions.

**slow**
1. You can fork this repository and drop pipenv support.
2. You can make pull request with proper support for both pipenv and pip
3. You can wait until I do required fixes.

I am very sorry for this situation. I will do my best to fix this problem this weekend. I'll let you know.

**Comment by akhilrajvc** [comment]
Hi @pawelzny 
Thanks for your quick response.

**Comment by pawelzny** [comment]
@akhilrajvc You can now install dotty 1.0.1 using PIP without any other dependencies.
`pip install dotty-dict==1.0.1`.

**Comment by akhilrajvc** [comment]
Working fine now.. thanks a lot @pawelzny
