### ISSUE TITLE
Dotty.pop(key, default) raises KeyError when key doesn't exist.

### ISSUE THREAD

**Issue by gilabrantes** [pawelzny/dotty_dict#48]
When default is given, Cut.pop(key, default) is expected to return default if key doesn't exist.

Reproducing steps:
```
Python 3.6.8 (default, Aug 20 2019, 17:12:48)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dotty_dict import dotty
>>> a = dotty()
>>> a.pop('does.not.exist', None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gil/.virtualenvs/Sandbox/lib/python3.6/site-packages/dotty_dict/dotty_dict.py", line 263, in pop
    return pop_from(self._split(key), self._data)
  File "/home/gil/.virtualenvs/Sandbox/lib/python3.6/site-packages/dotty_dict/dotty_dict.py", line 258, in pop_from
    data = data[it]
KeyError: 'does'
>>>
```

Ubuntu @ Windows Subsystem Linux | Windows 10

**Comment by Dysproz** [comment]
Hi @gilabrantes,

Thanks for your feedback.
I created a Pull Request that resolves this bug:
https://github.com/pawelzny/dotty_dict/pull/49

**Comment by pawelzny** [comment]
Hi @gilabrantes,

Fix has been merged to master. Please install dotty_dict from last commit and tell us if this solves your problem. If so, I will make a new release.

```
pip install git+git://github.com/pawelzny/dotty_dict.git@691f2d58c4340d68a816b62d2f12b0eb925ccff7
```

**Comment by gilabrantes** [comment]
Hello @pawelzny @Dysproz,

Apologies for the delay. The fix works fine, thank you.

```
Python 3.6.8 (default, Aug 20 2019, 17:12:48)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dotty_dict import dotty
>>> a = dotty()
>>> a.pop('does.not.exist', None)
>>>
```
I'll use the new release when it's ready.
Thanks!

**Comment by gilabrantes** [comment]
Hey @pawelzny,

Any ETA for the next release including the fix?

Thanks!
Gil

**Comment by Dysproz** [comment]
@gilabrantes 

We'll release it today. :)
Something around 18-20 CEST.

**Comment by pawelzny** [comment]
@gilabrantes release is ready to download https://pypi.org/project/dotty-dict/1.2.1/

```
pip install dotty-dict==1.2.1
```

**Comment by gilabrantes** [comment]
Thank you very much!
