### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by alita91** [pawelzny/dotty_dict#52]
When I try to see if a key exist in the dotty dict by using "in", I receive an IndexError

if key in dot:
   pass

The input that I give is "something.0', line number is 103, in search_in method

Thanks

**Comment by Dysproz** [comment]
Hi @alita91,
Thank you for your feedback.
I took a closer look at this problem and I created a Pull Request that should fix it - #54

**Comment by Dysproz** [comment]
Hi @alita91,
Sorry that it took so long, but the fix is merged to master.
Can you please install dotty from master branch, test whether your problem is fixed and let me know? :)
`pip install git+git://github.com/pawelzny/dotty_dict.git`

**Comment by Dysproz** [comment]
Closing this bug as fix is in master branch for a long time
