### ISSUE TITLE
Request: Need a way to access the list elements using square brackets

### ISSUE THREAD

**Issue by alita91** [pawelzny/dotty_dict#53]
Hello guys,

I need a way to access the list elements from a dotty dict by using square brackets, here is an example:

dict['something.0.other'] => dict['something[0].other']

Could you please tell me if is possible to have this implemented in future?

Thanks

**Comment by Dysproz** [comment]
Hi @alita91,
Thanks for your feedback! :)
May I ask you to give me some more details on a use case that'd require using square brackets?

**Comment by alita91** [comment]
Hi @Dysproz 

I have a couple of scripts who actually require this feature, because I'm calling some other external programs that need input in this format, like helm.

helm upgrade. \
  --set ingress.tls[0].hosts="{my.url.net}" \
  --set ingress.tls[0].hosts.secretName=tls-secret \

It will be great if you can cover this case as well, I'm not sure how hard will be.

Thanks

**Comment by simonvadee** [comment]
I also need this! The dot-notated path I work with also use brackets to represent indices, and I'd like to avoid pre-processing the path before passing it to dotty.

**Comment by Dysproz** [comment]
@alita91, @simonvadee,
First of all, sorry that it took me so long.

I considered additional logic for lists with brackets, but I'd prefer not to add it into Dotty's code. Additional conditional functions would make it pretty messy.

I think that it'll be easier to just add simple operation in your code on string with brackets and then paste result into dotty. Here's an example:
```
>>> bracket_path = 'ingress.tls[0].hosts'
>>> dot_path = bracket_path.replace('[', '.').replace(']', '')
>>> dot_path
'ingress.tls.0.hosts'
```

I hope that it'll make it for you guys. :)
