### ISSUE TITLE
do not convert numeric keys to indexes

### ISSUE THREAD

**Issue by pierwszywolny** [pawelzny/dotty_dict#58]
Having a choice how to treat ints was a great option.
It was possible to decide how to deal with 'KeyA.1.KeyB' in 1.1.2 but unfortunalelly it was removed.

**Comment by Dysproz** [comment]
Yes, but in fact that feature didn’t work with really deep dictionaries.
Current solution works properly with lists nested on different dictionary levels or lists on lists. It’s more universal.

Probably adding optional argument to treat int as key wouldn’t be that hard, but I’m not sure whether that’s be such a great design.
@pawelzny what do you think?

**Comment by Dysproz** [comment]
@pierwszywolny,
My PR has just been merged.

Now you can provide additional flag on dotty dict creation `no_list` which will turn off lists fetures and all keys will be treated as string dictionary keys. :)
