### ISSUE TITLE
Return all in a list

### ISSUE THREAD

**Issue by coolacid** [pawelzny/dotty_dict#60]
I'd love to be able to return a list based on a wildcard character, example:

```
dot = dotty({
    'annotations': [
        {'label': 'app', 'value': 'webapi'},
        {'label': 'role', 'value': 'admin'},
    ],
    'spec': {
         'containers': [
             ['gpu', 'tensorflow', 'ML'],
             ['cpu', 'webserver', 'sql'],
        ]
    }
})
```

`dot['annotations.*.label']` would return: `["app", "role"]`

**Comment by Dysproz** [comment]
Hi @coolacid,
Sorry for late response. Thanks for your for post.

That's really good idea. I'll check what I can do to implement that. :)

**Comment by Dysproz** [comment]
@coolacid,
My PR has just been merged into master.
Now you can access lists with python list slices.

You may find examples in Advanced section of our docs. For your request it’ll be `dot[“annotations.:.label”]`.

Thanks for great idea! :D
