### ISSUE TITLE
Cannot serialize a dotty object with dotty objects

### ISSUE THREAD

**Issue by wsw70** [pawelzny/dotty_dict#62]
First of all - thanks a lot (dziekuję :)) for dotty_dict. It wonderfully simplifies my code.

I ran into an issue when trying to serialize some nested `dotty()` objects because `.to_dict()` does not process them:

```
>>> from dotty_dict import dotty 
>>> a = dotty()
>>> a['hello.world'] = 1
>>> b = dotty()
>>> b['wazaa'] = 3
>>> a['nested.dotty'] = b
>>> a
Dotty(dictionary={'hello': {'world': 1}, 'nested': {'dotty': Dotty(dictionary={'wazaa': 3}, separator='.', esc_char='\\')}}, separator='.', esc_char='\\')
>>> a.to_dict()
{'hello': {'world': 1}, 'nested': {'dotty': Dotty(dictionary={'wazaa': 3}, separator='.', esc_char='\\')}}
>>> import json
>>> json.dumps(a)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\Python38-32\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files (x86)\Python38-32\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files (x86)\Python38-32\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files (x86)\Python38-32\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Dotty is not JSON serializable
```

It may be worthwhile to add this to the docs and suggest to `.to_dict()` the intermediate object.

BTW it took me some time to find out how to convert a `dotty()` object to a `dict`, fortunately this was in one of the examples.

**Comment by Dysproz** [comment]
Hi @wsw70,
Thanks for your post.

I'll take a look into our code and try to find some solution to recursively convert all nested Dotty instances into dictionaries.
However, it may be hard to make it as for really big nested dictionaries, it'll be just ineffective.

**Comment by Dysproz** [comment]
@wsw70,
My PR with fix for your issue has been just merged.

From now on `.to_dict()` will return dictionary without nested dotty objects - only standard Python serialisable types.

Moreover, if you need json representation as string then you may now use method `.to_json()` which will basically return the same outputs as you'd rum `json.dumps(dot.to_dict())`. :)

**Comment by wsw70** [comment]
@Dysproz Thanks a lot!
