### ISSUE TITLE
List slices don't work as outlined in documented advanced examples

### ISSUE THREAD

**Issue by digitalformula** [pawelzny/dotty_dict#67]
I'm trying to use `dotty-dict` with list slices so that I can iterate over lists with potentially unknown field names.  To try this I'm using the documented examples, but they don't work as shown.  Example of my usage, as per the docs:

```
   ~/Da/s/nu/u/H/eval    main !2 ?4 ❯ python3.8                                                          eval   18:40:03
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from dotty_dict import dotty
>>> dot = dotty({
...     'annotations': [
...         {'label': 'app', 'value': 'webapi'},
...         {'label': 'role', 'value': 'admin'},
...         {'label': 'service', 'value': 'mail'},
...         {'label': 'database', 'value': 'postgres'}
...     ],
... })
>>> assert dot['annotations.:.label'] == ['app', 'role', 'service', 'database']
Traceback (most recent call last):
  File "/home/c/hce/eval/venv/lib/python3.8/site-packages/dotty_dict/dotty_dict.py", line 131, in get_from
    data = data[it]
TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c/hce/eval/venv/lib/python3.8/site-packages/dotty_dict/dotty_dict.py", line 139, in __getitem__
    return get_from(self._split(item), self._data)
  File "/home/c/hce/eval/venv/lib/python3.8/site-packages/dotty_dict/dotty_dict.py", line 135, in get_from
    return get_from(items, data)
  File "/home/c/hce/eval/venv/lib/python3.8/site-packages/dotty_dict/dotty_dict.py", line 133, in get_from
    raise KeyError("List index must be an integer, got {}".format(it))
KeyError: 'List index must be an integer, got :'
>>>
```

The other documented examples work without any issues.

**Comment by digitalformula** [comment]
Bump?  I asked a question on Reddit about this and the person that answered has the same issue above.

**Comment by Dysproz** [comment]
Hi @digitalformula,
Thanks for your issue.
Which version of dotty_dict are you using? Is it downloaded form PyPI?
If so then I think that @pawelzny missed the relase of changes that I've made on July regarding this problem.

I've just checked with code in master branch and above example works for me.
@pawelzny may you make a code release to PyPI?

**Comment by Dysproz** [comment]
@digitalformula I see that Paweł has just released the new version of dotty-dict. Upgrade to version 1.3.0 and check now :)

**Comment by pawelzny** [comment]
Hi @digitalformula please install the new version 1.3.0 from PyPI `pip install dotty-dict==1.3.0`.

**Comment by digitalformula** [comment]
Hi @pawelzny and @Dysproz - apologies for not answering this for so long.  Email notification got lost.  I can confirm that v1.3.0 does fix this issue.  Thank you!
