### ISSUE TITLE
Special characters in the author's name

### ISSUE THREAD

**Issue by vaclav-2012** [pawelzny/dotty_dict#69]
The author's name contains special characters that prevent the installation on Windows with Japanese encoding.

pip raises the following error:

```
File "C:\Users\test\AppData\Local\Temp\pip-install-qogza7z4\dotty-dict\setup.py", line 16, in <module>
        readme = readme_file.read()
UnicodeDecodeError: 'cp932' codec can't decode byte 0x82 in position 119: illegal multibyte sequence
```

**Comment by Dysproz** [comment]
Hi @vaclav-2012 
I've created PR where I replace Polish letters with standard Latin letters (PR #70 ).

**Comment by vaclav-2012** [comment]
Hi @Dysproz, Thank you for making the fix. Since the error was rasied by [this line](https://github.com/pawelzny/dotty_dict/blob/98984911a61ae9f1aa4da3f6c4808da991b89847/setup.py#L16) it may be safer to replace the Polish letters also in the README.rst file.

**Comment by Dysproz** [comment]
@vaclav-2012 I've created PR #72 to remov eit from README.rst as well. Thank you :)

**Comment by vaclav-2012** [comment]
@Dysproz Thank you for the update.

**Comment by Dysproz** [comment]
PR has been merged. May you check whether it works for you now? It is local install, isn't it? So we don't have to release immediately new package to PyPI.

**Comment by vaclav-2012** [comment]
The error appears during the installation from PyPI. Could you publish it to https://test.pypi.org for testing purposes? I can try to install the new version from https://test.pypi.org.

**Comment by Dysproz** [comment]
@pawelzny would you mind publishing it? You have the keys :)

**Comment by skullydazed** [comment]
We have [some users affected by this](https://github.com/qmk/qmk_firmware/pull/12127#issuecomment-797843231). Would it be possible to get a new package published?

**Comment by methane** [comment]
You can use `encoding="utf-8"` instead of removing non ASCII character from README.

See https://github.com/pypa/packaging.python.org/pull/682

For workaround, you can set `PYTHONUTF8=1` environment variable to make Python use UTF-8 as the default text encoding even on Windows.
