### ISSUE TITLE
Handling key with None value

### ISSUE THREAD

**Issue by LMIdimamura** [pawelzny/dotty_dict#81]
In version 1.2.1, if you tried: dot('ParentWithNoneValue.Child') it would return None. However, on version 1.3.0, the same syntax returns exception TypeError: argument of type 'NoneType' is not iterable.

I had to downgrade to version 1.2.1, could you please keep the behaviour the same as 1.2.1? Thank you.

**Comment by dannym87** [comment]
Just came across this issue too - cheers for the downgrade temporary solution.

+1 to keep 1.3.0 behaving the same way as 1.2.1.
